### ISSUE TITLE
[advanced example] feed.author subquery fails when using variables

### ISSUE THREAD

**Issue by timsuchanek** [graphql-boilerplates/node-graphql-server#109]
Query
```graphql
query ($where: UserWhereInput) {
  feed {
    id
    title
    author(where: $where) {
      id
    }
  }
}
```
Variables
```json
{
  "where": {
    "email": "a@a.de"
  }
}
```

Response
```json
{
  "data": null,
  "errors": [
    {
      "message": "Variable \"$where\" got invalid value {\"isPublished\":true}; Field \"isPublished\" is not defined by type UserWhereInput.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "feed"
      ]
    }
  ]
}
```

It seems that the variable `$where` gets the wrong value applied.

**Comment by kbrandwijk** [comment]
UserWhereInput doesn't have 'isPublished'. PostWhereInput does. So the error message is correct, right?

**Comment by marktani** [comment]
looks like something goes south because of the `where` defined here: https://github.com/graphql-boilerplates/node-graphql-server/blob/master/advanced/src/resolvers/Query.js#L5

@timsuchanek can you try to rename `$where` in your query to `$myWhere`, to see if this fixes the problem?

**Comment by marktani** [comment]
Closing in favor of https://github.com/graphcool/prisma-binding/issues/73.
