### ISSUE TITLE
Enabled debug by default

### ISSUE THREAD

**Issue by marktani** [graphql-boilerplates/node-graphql-server#111]

**Comment by kbrandwijk** [comment]
There will be a second debug option (from apollo-server options) in the next yoga release. So if you want to enable debug by default, you should also consider that option.

**Comment by marktani** [comment]
I added `debug: true` like this:

```js
    db: new Graphcool({
      typeDefs: 'src/generated/graphcool.graphql',
      endpoint: '__GRAPHCOOL_ENDPOINT__',
      secret: 'mysecret123',
      debug: true,
    }),
```

Do you see a downside of this compared to the `apollo-server` option?
