### ISSUE TITLE
Update boilerplate setup

### ISSUE THREAD

**Issue by kbrandwijk** [graphql-boilerplates/node-graphql-server#112]
- [X] Call `gc deploy` from install script
- [X] Remove default cluster from 'graphcool.yml'
- [ ] Ping nearest cluster (for fullstack only) -> on hold until graphcool cli offers this again
- [X] Write endpoint to .env after deployment

^^ In all boilerplates

**Comment by marktani** [comment]
why do you want to ping the nearest cluster? I think the local cluster is the preferred option.

**Comment by kbrandwijk** [comment]
As discussed with @schickling, for fullstack boilerplates/examples, the (nearest) new public cloud cluster should be the default. For server boilerplates, there should be no default.

**Comment by kbrandwijk** [comment]
@schickling Can we put the install script in a separate package, and require that in the `.install` folder, instead of copy pasting the same install script to each and every boilerplate? This would make it a lot more maintainable, and you always have only 1 dependency for installation.

**Comment by kbrandwijk** [comment]
Current version: see https://github.com/graphql-boilerplates/node-graphql-server/tree/installpathtest/basic/.install

**Comment by kbrandwijk** [comment]
https://github.com/graphcool/framework/issues/1525 is blocking for writing to the .env file
