### ISSUE TITLE
Now integration costly

### ISSUE THREAD

**Issue by lunchboxer** [graphql-boilerplates/node-graphql-server#118]
Installing the boilerplate works great until it gets to the now integration. I waited about five seconds for the rest of the package to download and install and the now cli is downloading... still, as I type. I don't know why it takes so long, but I also don't know why it's baked in to begin with. Is there anything special about graphcool that makes using now especially difficult? If a user wants to use now can't they just download the cli and use it? What is the advantage of integration? I don't use now so all I see is the cost, since it's still downloading.

**Comment by kbrandwijk** [comment]
I agree that it takes quite a lot of time to install. I think this could be left out, and replaced with a `install-now` npm script (for convenience). The initial workflow should be all about getting up and running ASAP. @schickling thoughts?

**Comment by schickling** [comment]
Yeah, I agree. Let's tackle this with content instead!

**Comment by marktani** [comment]
I removed the now dependency, thanks!
