### ISSUE TITLE
Make `graphcool` CLI as local dev dependency

### ISSUE THREAD

**Issue by schickling** [graphql-boilerplates/node-graphql-server#121]
- [x] Add `graphcool` to `devDependencies`
- [x] Add Graphcool related tasks to `scripts`

> Note: This also applies to all other boilerplates.

**Comment by marktani** [comment]
I added

```
    "graphcool": "graphcool",
```

allowing you to run `yarn graphcool <command>`, for example `yarn graphcool deploy`. Did you have something else in mind?
