### ISSUE TITLE
Couldn't find graphcool.yml file

### ISSUE THREAD

**Issue by marktani** [graphql-boilerplates/node-graphql-server#136]
```sh
graphql create test # choose node-basic
```

results in this error

```sh
Running $ graphcool deploy...
 ▸    Couldn't find `graphcool.yml` file. Are you in the right directory?
```

```sh
gc version
graphcool/1.0.0-alpha3.3.5 (darwin-x64) node-v8.3.0

graphql -v
2.10.0
```

**Comment by kbrandwijk** [comment]
Did this occur after moving graphcool.yml to the database folder? How does the graphcool cli deal with that?

**Comment by marktani** [comment]
Yes! Turns out picking up the path to `graphcool.yml` from `.graphqlconfig.yml` is supported since `1.0.0-alpha3.3.7`, so I'm going to update that dependency 🙂
