### ISSUE TITLE
Playground not showing up the left "app/database" pane.

### ISSUE THREAD

**Issue by emipc** [graphql-boilerplates/node-graphql-server#152]
I was following the [Node.js Graphcool Quickstart](https://www.graph.cool/docs/1.0/quickstart/backend/node/node-phe8vai1oo) tutorial and, after running `graphcool playground`, I couldn't see the left pane with the two GraphQL APIs (app and database) shown in step 5.

Same happens with playground standalone version.

graphcool --version
`graphcool/1.0.0-beta4.1.1 (windows-x64) node-v8.9.4`
`graphql-cli@2.12.1`

package.json
```
{
  "name": "my-app",
  "scripts": {
    "start": "cross-env NODE_ENV=dev node src/index.js",
    "playground": "graphcool playground"
  },
  "dependencies": {
    "graphcool-binding": "1.3.5",
    "graphql-yoga": "^1.1.5"
  },
  "devDependencies": {
    "cross-env": "^5.1.3",
    "graphcool": "1.0.0-beta4.1.1"
  }
}
```

I've just modified the `start` script adding `cross-env` to make  it compatible with Windows.

**Comment by emipc** [comment]
I was running `graphcool playground` instead of `graphql playground`. My fault!

**Comment by kbrandwijk** [comment]
Well, both the start script should use the `graphql playground` instead, and also the instructions in the tutorial are wrong, because `graphcool playground` will not show you what you see in the tutorial. @marktani

**Comment by marktani** [comment]
Please upgrade `graphql-yoga` to `1.2.0` and setup these scripts:

```
  "scripts": {
    "start": "nodemon -e js,graphql -x node -r dotenv/config src/index.js",
    "debug": "nodemon -e js,graphql -x node --inspect -r dotenv/config src/index.js",
    "playground": "graphql playground",
    "dev": "npm-run-all --parallel start playground"
  },
```

`yarn dev` will start the server, and also a separate process for the Playground webserver (if you don't have electron installed). This should display both projects to the left.

**Comment by nikolasburk** [comment]
I just updated the quickstart tutorials and fixed the issues, thanks for bringing this up @emipc! 🙌
