### ISSUE TITLE
graphql-cli devdependency missing in advanced template

### ISSUE THREAD

**Issue by kbrandwijk** [graphql-boilerplates/node-graphql-server#154]
It uses `graphql playground` as one of the scripts.

**Comment by marktani** [comment]
You run `graphql create` to get the boilerplate. So you already have `graphql` installed.

**Comment by kbrandwijk** [comment]
Then it should be removed from the typescript-advanced, that was my point of reference.

**Comment by kbrandwijk** [comment]
@marktani Actually, thinking about it, I don't agree. The person _creating_ this using the boilerplate might have it installed, but any team member _using_ the output of the boilerplate doesn't necessarily have it.

**Comment by kbrandwijk** [comment]
@nikolasburk This is also for typescript templates. They also miss this devDependency.

**Comment by nikolasburk** [comment]
Thanks for reporting this, fixed now 🙌
