### ISSUE TITLE
Error: Duplicate "graphql" modules

### ISSUE THREAD

**Issue by tobkle** [graphql-boilerplates/node-graphql-server#211]
After starting with today's version (there is no version tag):
```bash
yarn dev
```
And running a posts query in the playground, I received the following error:
```bash
Server is running on http://localhost:4000
Serving playground at http://localhost:3000/playground
Error: Cannot use GraphQLSchema "[object Object]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

Solved it by 
* yarn clean cache
* npm -rf node_modules
* added in package.json the "resolutions" section
* yarn install
```javascript
{
  "name": "node-advanced",
  "scripts": {
    "start": "nodemon -e js,graphql -x node -r dotenv/config src/index.js",
    "debug": "nodemon -e js,graphql -x node --inspect -r dotenv/config src/index.js",
    "playground": "graphql playground",
    "dev": "npm-run-all --parallel start playground"
  },
  "dependencies": {
    "bcryptjs": "2.4.3",
    "graphql-yoga": "1.3.2",
    "jsonwebtoken": "8.1.1",
    "prisma-binding": "1.5.12"
  },
  "devDependencies": {
    "dotenv": "5.0.0",
    "graphql-cli": "2.14.1",
    "nodemon": "1.15.0",
    "npm-run-all": "4.1.2",
    "prisma": "1.2.4"
  },
  "resolutions": {
    "graphql": "^0.13.0",
    "**/graphql": "^0.13.0"
  }
}
```
Or is there a better way resolving this error situation?

**Comment by marktani** [comment]
Gey @tobkle, thanks for reporting this issue!

Could you try following the steps mentioned [in this comment](https://github.com/graphcool/graphql-yoga/issues/162#issuecomment-367368045)?

Let me know if that doesn't solve the problem for you.

Thanks! 🙏

**Comment by SebaBoler** [comment]
first : **yarn clean cache** need be replace by yarn cache clean * [Documentation Yarn](https://yarnpkg.com/en/docs/cli/cache)
second:  dont use **npm -rf node_modules** but **rm -rf node_modules**

**Comment by haysclark** [comment]
@tobkle It would be great if the "Answer" could be updated with the edits from @SebaBoler.

**Comment by AviIhej** [comment]
I followed all of these steps and still got the same result. Any idea why?

**Comment by AliIsawi** [comment]
this solution worked for me :
1. remove node_modules.
2. remove package-lock.json
3. run npm install again 

that's it

**Comment by codemaster08240328** [comment]
@tobkle , I followed the step you mentioned, still have same issue. 
Any idea why?
I added 
"resolutions": {
    "graphql": "^14.0.0",
    "**/graphql": "^14.0.0"
  },

**Comment by miketwo** [comment]
@codemaster08240328 If you search for graphql modules (`npm ls graphql` or `yarn list --pattern graphql`), are there duplicates with different versions? Where do they come from?

**Comment by lirenhao** [comment]
me too is 'Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.', exec 'npm ls graphql',result is 'npm ls graphql'

**Comment by marius-tafika** [comment]
yarn list graphql
example:  
graphql@15.8.0
graphql@14.8.0

make all graphql to same version (see package.json)

**Comment by JoshuaAlzate** [comment]
I am encountering this error after I bundled my node application using `webpack`. I followed the resolution above yet the error persist.

This is my `yarn list --pattern graphql`

```
yarn list v1.22.17
├─ @apollographql/apollo-tools@0.5.2
├─ @apollographql/graphql-playground-html@1.6.29
├─ @graphql-tools/merge@8.2.3
├─ @graphql-tools/mock@8.5.2
├─ @graphql-tools/schema@8.3.2
├─ @graphql-tools/utils@8.6.2
├─ graphql-query-complexity@0.7.2
├─ graphql-subscriptions@1.2.1
├─ graphql-tag@2.12.6
├─ graphql@15.8.0
└─ type-graphql@1.1.1
```

**Comment by ukesh-rajasekar** [comment]
> @codemaster08240328 If you search for graphql modules (`npm ls graphql` or `yarn list --pattern graphql`), are there duplicates with different versions? Where do they come from?
This is the error msg when i tried to run codegen:

    Error: Cannot use GraphQLScalarType "String" from another module or realm.

    Ensure that there is only one instance of "graphql" in the node_modules
    directory. If different versions of "graphql" are the dependencies of other
    relied on modules, use "resolutions" to ensure only one version is installed.

    https://yarnpkg.com/en/docs/selective-version-resolutions

    Duplicate "graphql" modules cannot be used at the same time since different
    versions may have different capabilities and behavior. The data from one
    version used in the function from another could produce confusing and
    spurious results.

I tried @miketwo approach, worked in my case.  

1.  yarn list --pattern graphql
2. noticed I have multiple graphql modules
      something like this below

```
yarn list v1.22.17
├─ @apollographql/apollo-tools@0.5.3
├─ @apollographql/graphql-language-service-interface@2.0.2
├─ @apollographql/graphql-language-service-parser@2.0.2
├─ @apollographql/graphql-language-service-types@2.0.2
├─ @apollographql/graphql-language-service-utils@2.0.2
├─ @graphql-typed-document-node/core@3.1.1
├─ apollo-graphql@0.9.6
├─ apollo-language-server@1.26.8
│  └─ graphql@15.8.0
├─ apollo@2.33.10
│  ├─ graphql-tag@2.12.4
│  └─ graphql@15.8.0
├─ graphql-tag@2.12.6
└─ graphql@16.3.0
```

3. Then made sure every graphql modules belongs to the same version (in my case it is 15.8.0)

**Comment by Zoli06** [comment]
I leave this comment to help others who did the same stupid mistake that I did. I have a folder structure like this:

```
project
├─ client
│  └─npm things
├─ server
│  └─npm things
└─npm things
```

I accidentally installed graphql in the project's root folder instead of the server folder. Even `npm ls graphql` didn't show that. Just removed it and the error has gone.
