### ISSUE TITLE
Missing peer dependency warnings

### ISSUE THREAD

**Issue by kbrandwijk** [graphql-boilerplates/node-graphql-server#23]
All boilerplates have missing dependencies 'graphql' and 'graphql-tools':
```
warning "graphcool-binding > graphql-schema-cache@0.3.1" has unmet peer dependency "graphql-tools@^2.4.0 || ^2.5.0 || ^2.6.0 || ^2.7.0".
warning "graphql-yoga > graphql-tools@2.13.0" has unmet peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0".
warning "graphql-yoga > apollo-upload-server@4.0.0-alpha.1" has unmet peer dependency "graphql@^0.11.0".
warning "graphql-yoga > graphql-subscriptions@0.5.5" has unmet peer dependency "graphql@^0.10.5 || ^0.11.3".
warning "graphql-yoga > subscriptions-transport-ws@0.9.4" has unmet peer dependency "graphql@^0.10.0 || ^0.11.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core@1.3.0" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-cache-control@0.0.7" has unmet peer dependency "graphql@^0.10.0 || ^0.11.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core > graphql-extensions@0.0.5" has unmet peer dependency "graphql@^0.10.0 || ^0.11.0".
warning "graphql-yoga > apollo-server-express > apollo-server-core > apollo-tracing@0.1.1" has unmet peer dependency "graphql@^0.10.0 || ^0.11.0".
```

**Comment by schickling** [comment]
That's a good point. Do you have any opinion on whether this should be resolved in the boilerplates or in `graphql-yoga`?

Maybe @stubailo wants to share his thoughts?

**Comment by kbrandwijk** [comment]
I'm not sure. There used to be an issue with multiple versions of graphql being installed at the same time. That's why the advice was to always make that a peer dep and install it only once, on the actual project level. So that would mean: add them in the boilerplate.

**Comment by stubailo** [comment]
I think this is because the new 0.12 graphql version was released, so we need to update our stuff to work with that, and list that in the peer dependencies. So I think this is actually npm working as needed.

**Comment by stubailo** [comment]
OK, just looked at this and it turns out there are some very significant breaking changes in `graphql@0.12` in several areas, so basically any tool based on `graphql` is going to have some things to work on to upgrade.

Unfortunately, there aren't release notes yet: https://github.com/graphql/graphql-js/releases/tag/v0.12.0

We're working on fixes for `graphql-tools` and hopefully will be able to maintain backwards compatibility, keep track here: https://github.com/apollographql/graphql-tools/pull/541

**Comment by schickling** [comment]
Thanks for looking into this @stubailo 👏

**Comment by kbrandwijk** [comment]
@stubailo If you look at the warnings, they are all for <= 0.11.x, so I don't think it has to do with that. I believe it has to do with those packages specifying graphql as a peer dependency, so the dependency needs to be added to the consuming project explicitly.

**Comment by stubailo** [comment]
I don't currently think so - you get the same warning for a wrong version that you get for a missing package. So my current diagnosis is that people who install the boilerplate are getting graphql 0.12, since nothing would work without it, but the peerDep thing is complaining about the version.

**Comment by kbrandwijk** [comment]
As the dependencies on the boilerplates itself are set correctly now, and also for all directly related libraries (yoga etc.), this is now out of our control.

**Comment by masumbillah** [comment]
## May be I face in same problem.

MSs-Mac-mini:twitter-app ms$ yarn add apollo-server-express graphql-tools
yarn add v1.3.2[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "apollo-server-express > apollo-server-core@1.3.2" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0
.12.0".
warning "apollo-server-express > apollo-server-core > apollo-cache-control@0.0.9" has incorrect peer dependency "graphql@^0.10.0 ||
^0.11.0 || ^0.12.0".
warning "apollo-server-express > apollo-server-core > apollo-tracing@0.1.3" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.
0 || ^0.12.0".
warning "apollo-server-express > apollo-server-core > graphql-extensions@0.0.7" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0".
warning " > graphql-tools@2.20.2" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0".
[4/4] 📃  Building fresh packages...
success Saved 2 new dependencies.
├─ apollo-server-express@1.3.2
└─ graphql-tools@2.20.2
✨  Done in 1.92s.
