### ISSUE TITLE
SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by MrBoutte101** [graphql-boilerplates/node-graphql-server#285]
looks like the removal of `isPublished: false` broke the resolvers for basic and advanced boilerplates in node and ts.

change here: https://github.com/graphql-boilerplates/node-graphql-server/commit/a3facbbdf86735ce9e2f4cf9f3f55f4d78a797ae

<img width="1066" alt="screen shot 2018-04-24 at 11 14 42 am" src="https://user-images.githubusercontent.com/15992455/39196680-bcc70ef4-47b0-11e8-9dba-e517f1f25395.png">

```
[ts]
Argument of type '{ data: { title: any; text: any; }; }' is not assignable to parameter of type '{ data: PostCreateInput; }'.
  Types of property 'data' are incompatible.
    Type '{ title: any; text: any; }' is not assignable to type 'PostCreateInput'.
      Property 'isPublished' is missing in type '{ title: any; text: any; }'.
```

**Comment by MrBoutte101** [comment]
nothing to see here folks. The issue is that I use NVM on my computer at work and because the configuration of our project I have node 6 running as the default :disappointed:

sorry @marktani and @nikolasburk

**Comment by marktani** [comment]
If I understood @nikolasburk correctly, we can still roll out a couple of improvements here, so reopening. Thanks for your feedback in any case @MrBoutte101 🙏

**Comment by nikolasburk** [comment]
I fixed the TS compiler error, thanks @MrBoutte101 🎉
