### ISSUE TITLE
after upgrading to Prisma 1.7 , there are no folders 

### ISSUE THREAD

**Issue by Gamezpedia** [graphql-boilerplates/node-graphql-server#302]
hi, 

after upgrading to Prisma 1.7 , when you do` graphql create testapp --boilerplate` and hit enter and `choose  node-advanced`, you will get no folders.

![image](https://user-images.githubusercontent.com/1169093/39398716-ada4fd12-4b22-11e8-856f-126321421a25.png)

**Comment by marktani** [comment]
Thanks a lot for bringing this up, @Gamezpedia, we're taking a look at this soon!

**Comment by marktani** [comment]
This looks related to: https://github.com/graphql-cli/graphql-cli/issues/277

**Comment by cktang88** [comment]
I have this issue as well

**Comment by marktani** [comment]
@cktang88, can you confirm that with the fix for https://github.com/graphql-cli/graphql-cli/issues/277, this is also fixed? 🙂

**Comment by cktang88** [comment]
@marktani  yes that fix also covers this. It has nothing to do with Prisma 1.7, the underlying issue was the adm-zip library in the cli.

**Comment by marktani** [comment]
Thanks so much @cktang88! 🙏
