### ISSUE TITLE
Errors while validating graphcool.yml

### ISSUE THREAD

**Issue by erichodges** [graphql-boilerplates/node-graphql-server#36]
When I ran graphcool deploy I got these errors:

```
[ERROR] in /Users/erichodges/Documents/graphcool/graphql-boilerplate-1/graphcool.yml: Errors while validating graphcool.yml:

Error:   data should NOT have additional properties
   at Output.error (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Output/index.ts:164:15)
   at Object.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/ProjectDefinition/yaml.ts:38:9)
   at step (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/ProjectDefinition/yaml.js:32:23)
   at Object.next (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/ProjectDefinition/yaml.js:13:53)
   at fulfilled (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/ProjectDefinition/yaml.js:4:58)
   at <anonymous>
Exiting with code: 1
```

**Comment by kbrandwijk** [comment]
Could you try the recommendation from https://github.com/graphcool/graphql-server-example/issues/12#issuecomment-352213080? (install `graphcool@beta`?)

**Comment by marktani** [comment]
also, how does your `graphcool.yml` file look like?

**Comment by erichodges** [comment]
Hi, I did the graphcool@beta install and it seemed to work. I got a database endpoint.

When I go to the endpoint in Chrome I get this message:

Schema could not be fetched.
Please check if the endpoint 'https://database-beta.graph.cool/api/graphql-boilerplate/us-west-1' is a valid GraphQL Endpoint.

Maybe this is normal because there is no Schema? I have not run yarn start yet...

**Comment by schickling** [comment]
Would you mind pasting your `graphcool.yml`?

**Comment by erichodges** [comment]
Ok I'll find it...

**Comment by erichodges** [comment]
service: graphql-boilerplate

datamodel: database/datamodel.graphql

stages: 
  default: us-west-1
  us-west-1: shared-public-demo

**Comment by marktani** [comment]
Please see this common question: https://github.com/graphql-cli/graphql-boilerplate/tree/master/node-basic#im-getting-a-schema-could-not-be-fetched-error-after-deploying-what-gives

**Comment by erichodges** [comment]
Once I ran yarn start, I didn't get that message, so it's looking good.

**Comment by nikolasburk** [comment]
Seems like this issue was solved @erichodges? I'll close the issue for now, let me know if it comes up again 👍
