### ISSUE TITLE
no folders on advanced boilerplate install

### ISSUE THREAD

**Issue by okankayhan** [graphql-boilerplates/node-graphql-server#449]
Ubuntu
graphql-cli 3.0.3

This is what i get after running `graphql create my-app --boilerplate node-advanced`

![screenshot from 2018-12-26 10-00-41](https://user-images.githubusercontent.com/19187619/50436094-27d83000-08f5-11e9-9fa3-e6f6966fecc4.png)

Expected

![screenshot from 2018-12-26 10-00-41](https://camo.githubusercontent.com/0a88d5a743cf9af8c974f669d3d1ff3c6e02a3d8/68747470733a2f2f696d6775722e636f6d2f393566615573612e706e67)

**Comment by AndreaPontrandolfo** [comment]
yes, can confirm, i'm having the same issue.

**Comment by KedareshwarChaudhari** [comment]
I am also seeing the same issue

**Comment by tiagodurante** [comment]
i'm having the same problem. 😢

**Comment by mairamartinsk** [comment]
Same issue happening on **node-basic** install.

**Comment by okankayhan** [comment]
fixed after upgrading graphql-cli to 3.0.11
