### ISSUE TITLE
A Tutorial for the beta version

### ISSUE THREAD

**Issue by state0fmind** [graphql-boilerplates/node-graphql-server#47]
Would love to have a single page description about how graphcool deploy works in the projects created by the cli. How do I deploy it locally or on a private server.

**Comment by nikolasburk** [comment]
Hey @state0fmind, thanks a lot for opening this issue! This is a very Graphcool-specific question, so the actual [`graphcool/framework`](https://github.com/graphcool/framework/) repo is a better place to ask this, would you mind asking the question there? Thanks!

**Comment by nikolasburk** [comment]
Hey @state0fmind! Thanks a lot for your question :)

We already have an updated Quickstart tutorial for writing a Node server with Graphcool 1.0 [here](https://www.graph.cool/docs/1.0/quickstart/backend/node/node-phe8vai1oo). We're also going to add the quickstarts for the other frontend/backend technologies in the next few days. Also keep an eye on the reference docs where we'll add the content for [Clusters](https://www.graph.cool/docs/1.0/reference/cluster/configuration-eu2ood0she) and the [Graphcool Cloud](https://www.graph.cool/docs/1.0/reference/graphcool-cloud/hosting-neip8oosh2) soon.

**Comment by nikolasburk** [comment]
You can also check the READMEs of the examples in this organization for more info. You can keep track of the ones that are up-to-date in [this issue](#27)

**Comment by state0fmind** [comment]
I've been getting no such file or directory, open '/Users/state0fmind/.graphcool/config.yml' error whenever I try to setup dockr cluster through graphcool local start. And yes there's no such file in the filesystem. WHat am I doing wrong?

**Comment by nikolasburk** [comment]
Maybe try to upgrade to the newest versions:

```sh
npm install -g graphcool@beta # install the latest Graphcool CLI
graphcool local upgrade # download the latest Docker images
```

**Comment by state0fmind** [comment]
@nikolasburk That didn't solve the problem, I was able to solve the problem by manually creating a .graphcool/config.yml at my root folder. Finally I can work with the boilerplate, I still don't understand how it works thuogh 🔢
