### ISSUE TITLE
Wrong GRAPHCOOL_ENDPOINT at generation

### ISSUE THREAD

**Issue by Geekat-Manu** [graphql-boilerplates/node-graphql-server#48]
_When I generated project from graphql CLI **(I'm using graphql@beta)** :_ 

`graphql created %app_name%`

(Tested with **Advanced Typescript** and **Advanced Node**)

The **.env GRAPHCOOL_ENDPOINT** is : **http://localhost:60000/%app_name%/dev**

But need to be **http://localhost:60000/api/%app_name%/dev**

After this change, everything works great.

**Comment by nikolasburk** [comment]
The `/api` was removed in the latest version from the generated endpoints. Can you please try to update your Graphcool Docker images and see if you still need the `/api`?

```
# Install latest CLI beta
npm install -g graphcool@beta

# Upgrade Graphcool Docker images
graphcool local upgrade
```

**Comment by nikolasburk** [comment]
I'm closing the issue for now, let me know if you still have the issue and we can reopen it :)
