### ISSUE TITLE
Cannot read property 'getDeployEndpoint'

### ISSUE THREAD

**Issue by LuisUrrutia** [graphql-boilerplates/node-graphql-server#50]
I followed the instructions in the advanced example and I get this error:

>   config CWD /Users/luisurrutiaf/Projects/Personal/node-graphql-server/advanced +0ms
>   config HOME /Users/luisurrutiaf +2ms
>   config definitionDir /Users/luisurrutiaf/Projects/Personal/node-graphql-server/advanced +1ms
>   config definitionPath /Users/luisurrutiaf/Projects/Personal/node-graphql-server/advanced/graphcool.yml +0ms
>   cli command id deploy +0ms
>   cli:plugincache Got plugin from cache +0ms
>   cli:plugincache /Users/luisurrutiaf/Library/Caches/graphcool/plugins.json +0ms
>   cli:plugincache Got plugin from cache +2ms
>   cli:plugincache /Users/luisurrutiaf/Library/Caches/graphcool/plugins.json +0ms
>   plugins findCommand graphcool-cli-core +0ms
>   plugin requiring command +0ms
>   cli-engine:plugins:manager requiring /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core +0ms
>   cli-engine:plugins:manager required +672ms
>   plugin required command +676ms
>   deploy run +0ms
> 
> ? Please choose the cluster you want to deploy "dev" to
> TypeError: Cannot read property 'getDeployEndpoint' of undefined
>     at Client.get [as client] (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Client/Client.ts:132:29)
>     at Client.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/src/Client/Client.ts:383:40)
>     at step (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:32:23)
>     at Object.next (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:13:53)
>     at /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:7:71
>     at Promise (<anonymous>)
>     at __awaiter (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:3:12)
>     at Client.listProjects (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-engine/dist/Client/Client.js:293:16)
>     at Deploy.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/src/commands/deploy/index.ts:216:40)
>     at step (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/deploy/index.js:42:23)
>     at Object.next (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/deploy/index.js:23:53)
>     at /usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/deploy/index.js:17:71
>     at Promise (<anonymous>)
>     at __awaiter (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/deploy/index.js:13:12)
>     at Deploy.projectExists (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/dist/commands/deploy/index.js:208:16)
>     at Deploy.<anonymous> (/usr/local/lib/node_modules/graphcool/node_modules/graphcool-cli-core/src/commands/deploy/index.ts:160:21)
> Exiting with code: 1

**Comment by kbrandwijk** [comment]
As this issue is related to the `graphcool` CLI, it should be moved to https://github.com/graphcool/framework/issues

**Comment by marktani** [comment]
This will be fixed in the next `graphcool@`beta release, more information here: https://github.com/graphcool/framework/issues/1477.
