### ISSUE TITLE
Schema could not be fetched

### ISSUE THREAD

**Issue by gHashTag** [graphql-boilerplates/node-graphql-server#55]
Started the project as here:
https://github.com/graphql-boilerplates/node-graphql-server/tree/master/basic#getting-started

 ```yarn start``` 

Server is running on http://localhost:4000 

**app/ default**
endpoint: http://localhost:4000

 ```Unexpected token H in JSON at position 0```

{ "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJh …"} 

**database/ dev**
endpoint: https://dev.database-beta.graph.cool/api/my-app/dev

 `Schema could not be fetched.
Please check if the endpoint 'https://dev.database-beta.graph.cool/api/my-app/dev' is a valid GraphQL Endpoint.` 

I get a token through these steps:

 https://github.com/graphql-boilerplates/node-graphql-server/tree/master/basic#im-getting-a-schema-could-not-be-fetched-error-after-deploying-what-gives

But after refresh 

 ```Schema could not be fetched.
Please check if the endpoint 'https://dev.database-beta.graph.cool/api/my-app/dev' is a valid GraphQL Endpoint.```

  Where am I wrong?

**Comment by gHashTag** [comment]
Can the endpoint not be configured correctly?
https://github.com/graphql-boilerplates/node-graphql-server/blob/5a52491ace3a9e60ef3ad2ad20ab5d4785867d3e/basic/src/index.js#L39

**Comment by marktani** [comment]
* What's your `graphcool version`?
* What's the output of `docker ps`?

 Thanks! 🙂

**Comment by gHashTag** [comment]
duplicate  🙂
https://github.com/graphql-boilerplates/typescript-graphql-server/issues/8
