### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by mkozhukharenko** [graphql-boilerplates/node-graphql-server#61]
I have troubles with graphql-boilerplate:

1. `graphql create my-app`
select ‘advanced typescript’
2. `cd my-app`

3. `graphcool deploy` -> 
select ‘local’ and got ERROR: `Cannot read property 'getDeployEndpoint' of undefined`

deploying to shared-cluster works

Expected behaviour:
It should work or clear error should be printed

4. `yarn deploy` and got ERROR: `--dotenv flag is set but .env.prod file is missing`

Expected behaviour: there should be an instruciton about .env.prod file

**Comment by kbrandwijk** [comment]
If you have selected `advanced typescript`, you are actually using the boilerplate from the https://github.com/graphql-boilerplates/typescript-graphql-server repo. Could you post this there?

**Comment by mkozhukharenko** [comment]
closed in favour of https://github.com/graphql-boilerplates/typescript-graphql-server/issues/7

**Comment by mkozhukharenko** [comment]
closed in favour of https://github.com/graphql-boilerplates/typescript-graphql-server/issues/7
