### ISSUE TITLE
Cannot connect to DB

### ISSUE THREAD

**Issue by davidyin1212** [graphql-boilerplates/node-graphql-server#63]
Getting error from graphql playground:

> {
  "requestId": "api:api:cjbmqvwun000s0122f9u0yri4",
  "error": "Whoops. Looks like an internal server error. Please contact us from the Console (https://console.graph.cool) or via email (support@graph.cool) and include your Request ID: api:api:cjbmqvwun000s0122f9u0yri4"
}

This is happening locally.

**Comment by marktani** [comment]
This was resolved after running`graphcool local nuke`. **This will remove all local graphcool data, so be careful.**
