### ISSUE TITLE
Running boilerplate install script...  ✖  Unexpected token )

### ISSUE THREAD

**Issue by Illuday** [graphql-boilerplates/node-graphql-server#69]
**UBUNTU 16.04** with graphcool@beta **[1.0.0-beta2.1.1]** && graphql-cli@beta **[2.1.0-beta18]**

`$ graphql create %appName% --boilerplate node-advanced`

> (...)
> [graphql create] Running boilerplate install script... 
> ✖ 
> **Unexpected token )**

Other things : 

- Node : **7.10.1**
- Docker :  **17.09.1-ce**
- Docker-compose : **1.8.0**

Running `$ graphql create %appName%` : 

> ├─┬ graphcool-binding@0.2.4 
> │ ├─┬ @types/jsonwebtoken@7.2.5 
> │ │ └── @types/node@8.5.2 
> │ ├─┬ apollo-link@1.0.7 
> │ │ ├── apollo-utilities@1.0.3 
> │ │ └── zen-observable@0.6.1 
> │ ├── apollo-link-http@1.3.2 
> │ ├─┬ cross-fetch@1.1.1 
> │ │ └── whatwg-fetch@2.0.3 
> │ ├─┬ **UNMET PEER DEPENDENCY graphql@0.12.3**

> ├─┬ graphql-yoga@0.4.7 
> │ ├── @types/cors@2.8.3 
> │ ├─┬ @types/express@4.11.0 
> │ │ ├── @types/body-parser@1.16.8 
> │ │ ├── @types/express-serve-static-core@4.11.0 
> │ │ └─┬ @types/serve-static@1.13.1 
> │ │   └── @types/mime@2.0.0 
> │ ├── @types/zen-observable@0.5.3 
> │ ├─┬ apollo-server-express@1.3.2 
> │ │ ├─┬ apollo-server-core@1.3.2 
> │ │ │ ├─┬ apollo-cache-control@0.0.7 
> │ │ │ │ └── **UNMET PEER DEPENDENCY graphql@^0.10.0 || ^0.11.0**
> │ │ │ ├─┬ apollo-tracing@0.1.1 
> │ │ │ │ └── **UNMET PEER DEPENDENCY graphql@^0.10.0 || ^0.11.0**
> │ │ │ ├── **UNMET PEER DEPENDENCY graphql@^0.10.0 || ^0.11.0**

**Comment by kbrandwijk** [comment]
Could you retry this with the latest non-beta graphql-cli release?

**Comment by schickling** [comment]
This is fixed in the latest `graphql-cli` release.

**Comment by marcovc** [comment]
Just to say I'm seeing this on 2.12.4. Thanks. Marco

**Comment by kbrandwijk** [comment]
It has to do with the node version. It requires 8.something or 9.

**Comment by marcovc** [comment]
Yes, upgrading node to 9.0.0 solved it. Thank you!
